### ISSUE TITLE
FirefoxProfile isn't working

### ISSUE THREAD

**Issue by rohitkadam19** [juliemr/protractor-demo#23]
I am running howtos/setFirefoxProfile/conf.js and during wait period trying to open new tab.
New tab is not showing angular.org page. It means not able to set profile.

Also getting below error -
# apps@apps-thinkpad-w530:~/Downloads/UStax/protractor-demo-master$ ./node_modules/protractor/bin/protractor howtos/setFirefoxProfile/conf.js 

Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://10.97.123.140:32825/wd/hub

/home/apps/Downloads/UStax/protractor-demo-master/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113
  var template = new Error(this.message);
                 ^
UnknownError: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}
1467886981535   addons.xpi  INFO    Mapping ubufox@ubuntu.com to /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi
1467886981535   addons.xpi  DEBUG   checkForChanges
1467886981536   addons.xpi  DEBUG   Loaded add-on state from prefs: {"app-profile":{"fxdriver@googlecode.com":{"d":"/tmp/anonymous8110263991387900314webdriver-profile/extensions/fxdriver@googlecode.com","e":false,"v":"2.45.0","st":1467886970000,"mt":1467886970000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"44.0","st":1454042676000,"mt":1453731169000}},"app-system-share":{"ubufox@ubuntu.com":{"d":"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi","e":false,"v":"3.2","st":1442597167000}}}
1467886981537   addons.xpi  DEBUG   Existing add-on fxdriver@googlecode.com in app-profile
1467886981537   addons.xpi  DEBUG   getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1467886981538   addons.xpi  DEBUG   Existing add-on {972ce4c6-7e08-4474-a285-3208198ce6fd} in app-global
1467886981538   addons.xpi  DEBUG   Existing add-on ubufox@ubuntu.com in app-system-share
1467886981538   addons.xpi  DEBUG   getInstallState changed: false, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"/tmp/anonymous8110263991387900314webdriver-profile/extensions/fxdriver@googlecode.com","e":false,"v":"2.45.0","st":1467886970000,"mt":1467886970000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"44.0","st":1454042676000,"mt":1453731169000}},"app-system-share":{"ubufox@ubuntu.com":{"d":"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi","e":false,"v":"3.2","st":1442597167000}}}
1467886981540   addons.xpi  DEBUG   No changes found
1467886981547   addons.manager  DEBUG   Registering shutdown blocker for XPIProvider
1467886981549   addons.manager  DEBUG   Provider finished startup: XPIProvider
1467886981549   addons.manager  DEBUG   Starting provider: LightweightThemeManager
1467886981549   addons.manager  DEBUG   Registering shutdown blocker for LightweightThemeManager
1467886981550   addons.manager  DEBUG   Provider finished startup: LightweightThemeManager
1467886981551   addons.manager  DEBUG   Starting provider: GMPProvider
1467886981564   addons.manager  DEBUG   Registering shutdown blocker for GMPProvider
1467886981565   addons.manager  DEBUG   Provider finished startup: GMPProvider
1467886981565   addons.manager  DEBUG   Starting provider: PluginProvider
1467886981565   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
1467886981566   addons.manager  DEBUG   Provider finished startup: PluginProvider
1467886981567   addons.manager  DEBUG   Completed startup sequence
1467886981667   addons.xpi-utils    DEBUG   Starting async load of XPI database /tmp/anonymous8110263991387900314webdriver-profile/extensions.json
**\* Blocklist::_loadBlocklistFromFile: blocklist is disabled
1467886981787   addons.manager  DEBUG   Starting provider: <unnamed-provider>
1467886981787   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
1467886981788   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
1467886982148   addons.xpi-utils    DEBUG   Async JSON file read took 0 MS
1467886982148   addons.xpi-utils    DEBUG   Finished async read of XPI database, parsing...
1467886982194   addons.xpi-utils    DEBUG   Successfully read XPI database
1467886982338   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
1467886982338   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
1467886982338   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider
JavaScript warning: https://normandy.cdn.mozilla.net/static/js/bundles/selfrepair-7575f6d27445b45bcffb.js, line 9825: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

```
at new bot.Error (/home/apps/Downloads/UStax/protractor-demo-master/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:113:18)
at Object.bot.response.checkResponse (/home/apps/Downloads/UStax/protractor-demo-master/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/response.js:106:9)
at /home/apps/Downloads/UStax/protractor-demo-master/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:158:24
at [object Object].promise.ControlFlow.runInFrame_ (/home/apps/Downloads/UStax/protractor-demo-master/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1877:20)
at [object Object].promise.Callback_.goog.defineClass.notify (/home/apps/Downloads/UStax/protractor-demo-master/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:2464:25)
at [object Object].promise.Promise.notify_ (/home/apps/Downloads/UStax/protractor-demo-master/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:563:12)
at Array.forEach (native)
at Object.goog.array.forEach (/home/apps/Downloads/UStax/protractor-demo-master/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/array/array.js:203:43)
at [object Object].promise.Promise.notifyAll_ (/home/apps/Downloads/UStax/protractor-demo-master/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:552:16)
at goog.async.run.processWorkQueue (/home/apps/Downloads/UStax/protractor-demo-master/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:125:21)
```

From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/home/apps/Downloads/UStax/protractor-demo-master/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:155:22)
    at Function.webdriver.WebDriver.createSession (/home/apps/Downloads/UStax/protractor-demo-master/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:129:30)
    at [object Object].Builder.build (/home/apps/Downloads/UStax/protractor-demo-master/node_modules/protractor/node_modules/selenium-webdriver/builder.js:416:22)
    at [object Object].DriverProvider.getNewDriver (/home/apps/Downloads/UStax/protractor-demo-master/node_modules/protractor/lib/driverProviders/driverProvider.js:38:7)
    at [object Object].Runner.createBrowser (/home/apps/Downloads/UStax/protractor-demo-master/node_modules/protractor/lib/runner.js:180:37)
    at /home/apps/Downloads/UStax/protractor-demo-master/node_modules/protractor/lib/runner.js:268:21
    at _fulfilled (/home/apps/Downloads/UStax/protractor-demo-master/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/home/apps/Downloads/UStax/protractor-demo-master/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/home/apps/Downloads/UStax/protractor-demo-master/node_modules/q/q.js:759:13)
    at /home/apps/Downloads/UStax/protractor-demo-master/node_modules/q/q.js:573:44
[launcher] Process exited with error code 1

Protractor version - 2.1.0
Firefox - 44
Selenium-webdriver - 2.45.0

**Comment by writetocynthia** [comment]
Yes I tried this too it kicks off the firefox browser and you can see it open but it does not run anything.

**Comment by meenakshidembi** [comment]
This npm isn't working properly for me as well.

**Comment by christopher-fredregill-rs** [comment]
+1

**Comment by jmcollin78** [comment]
Firefox profile is not loaded for me. I see those messages in webdriver-start window:
```
08:21:28.708 INFO - Executing: [new session: Capabilities [{count=1, browserName=firefox, firefox_profile=UEsDBBQACAAIAK46QkoAAAAAAAAAA...}]])
08:21:28.709 INFO - Creating a new session for Capabilities [{count=1, browserName=firefox, firefox_profile=UEsDBBQACAAIAK46QkoAAAAAAAAAA...}]
08:21:36.168 INFO - Done: [new session: Capabilities [{count=1, browserName=firefox, firefox_profile=UEsDBBQACAAIAK46QkoAAAAAAAAAA...}]]
```

SO it seems that a profile have been loaded. But regarding to firefox options don't show any of my options.
```
 $ firefox --version
Mozilla Firefox 45.7.0
 $ uname -a
Linux localhost.localdomain 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by marklagendijk** [comment]
See #26 and #28 for a working version.
